In [23]:
import pandas as pd
df = pd.read_csv("../2021.csv")
df.head(4)

,ID,Category,Segment,Region,First Supplying Date,Last Supplying Date,Is Currently Churned (Yes / No),Store Item Daily Count Items,Store Item Daily Total Supply,Store Item Daily Count Items.1,...,Store Item Daily Count Items.360,Store Item Daily Total Supply.360,Store Item Daily Count Items.361,Store Item Daily Total Supply.361,Store Item Daily Count Items.362,Store Item Daily Total Supply.362,Store Item Daily Count Items.363,Store Item Daily Total Supply.363,Store Item Daily Count Items.364,Store Item Daily Total Supply.364
0,77070,Indie - Inbound,Supermarket Small,Vaud,NaN,NaN,No,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,200989,Indie - Inbound,Traditional Restaurant,Valais,NaN,NaN,No,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,220661,Key Account,Supermarket Small,Bern,NaN,NaN,No,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,220695,Key Account,Supermarket Small,Bern,NaN,NaN,Yes,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
region_type = {"Vaud": "urban", 
           "Zürich": "urban",
           "St. Gallen": "urban", 
           "Valais": "rural", 
           "Bern": "urban", 
           "Ticino": "urban", 
           "Genève": "urban", 
           "Aargau": "rural", 
           "Basel-Stadt": "urban", 
           "Thurgau": "rural",
           "Luzern": "urban",
           "Obwalden": "rural",
           "Solothurn": "rural",
           "Graubünden": "rural",
           "Basel-Landschaft": "rural",
           "Freiburg": "urban",
           "Neuchâtel": "urban",
           "Zug": "urban",
           "Schwyz": "rural",
           "Schaffhausen": "rural",
           "Appenzell Ausserrhoden": "rural",
           "Appenzell Innerrhoden": "rural",
           "Jura": "rural",
           "Uri": "rural",
           "Glarus": "rural",
           "Nidwalden": "rural"}

In [33]:
region_language = {"Vaud": "french", 
           "Zürich": "german",
           "St. Gallen": "german", 
           "Valais": "french", 
           "Bern": "german", 
           "Ticino": "italien", 
           "Genève": "french", 
           "Aargau": "german", 
           "Basel-Stadt": "german", 
           "Thurgau": "german",
           "Luzern": "german",
           "Obwalden": "german",
           "Solothurn": "german",
           "Graubünden": "german",
           "Basel-Landschaft": "german",
           "Freiburg": "french",
           "Neuchâtel": "french",
           "Zug": "german",
           "Schwyz": "german",
           "Schaffhausen": "german",
           "Appenzell Ausserrhoden": "german",
           "Appenzell Innerrhoden": "german",
           "Jura": "french",
           "Uri": "german",
           "Glarus": "german",
           "Nidwalden": "german"}

In [38]:
df["language"] = df["Region"].map(region_language)
df["region_type"] = df["Region"].map(region_type)

In [41]:
def region_feature(df):
    df["region_language"] = df["Region"].map(region_language)
    df["region_type"] = df["Region"].map(region_type)
    return df

In [43]:
def supply_change(df):
    df["supply_variation"] = df["Total Supply"] - df["Declared Supply"]
    return df

In [45]:
region_feature(df)

,ID,Category,Segment,Region,First Supplying Date,Last Supplying Date,Is Currently Churned (Yes / No),Store Item Daily Count Items,Store Item Daily Total Supply,Store Item Daily Count Items.1,...,Store Item Daily Total Supply.361,Store Item Daily Count Items.362,Store Item Daily Total Supply.362,Store Item Daily Count Items.363,Store Item Daily Total Supply.363,Store Item Daily Count Items.364,Store Item Daily Total Supply.364,language,region_type,region_language
0,77070,Indie - Inbound,Supermarket Small,Vaud,NaN,NaN,No,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,french,urban,french
1,200989,Indie - Inbound,Traditional Restaurant,Valais,NaN,NaN,No,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,french,rural,french
2,220661,Key Account,Supermarket Small,Bern,NaN,NaN,No,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,german,urban,german
3,220695,Key Account,Supermarket Small,Bern,NaN,NaN,Yes,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,german,urban,german
4,220697,Key Account,Supermarket Small,Bern,NaN,NaN,Yes,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,german,urban,german
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5903,11286,Indie - Outbound,Sushi,Luzern,2016-06-03,2022-02-16,No,1.0,0.0,1.0,...,3.0,1.0,3.0,1.0,3.0,1.0,3.0,german,urban,german
5904,11295,Indie - Outbound,Fast Food / Take away restaurant,Zürich,2016-05-28,2022-02-16,No,1.0,0.0,1.0,...,2.0,1.0,0.0,1.0,0.0,1.0,0.0,german,urban,german
5905,11294,Indie - Outbound,Fast Food / Take away restaurant,Zürich,2016-05-23,2022-02-16,No,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,german,urban,german
5906,11279,Indie - Outbound,Cafeteria,Zürich,2016-04-20,2022-02-16,No,1.0,0.0,1.0,...,6.0,1.0,6.0,1.0,3.0,1.0,6.0,german,urban,german
5907,11283,Indie - Outbound,Sushi,Luzern,2016-04-16,2022-02-16,No,1.0,8.0,1.0,...,3.0,1.0,2.0,1.0,4.0,1.0,3.0,german,urban,german